-- local function my_on_attach(bufnr)
--     local api = require "nvim-tree.api"
--
--     local function opts(desc)
--         return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
--     end
--
--     -- Default mappings
--     api.config.mappings.default_on_attach(bufnr)
--
--     -- Custom mappings
--     vim.keymap.set('n', 'l', api.node.open.edit, opts('Open'))
--     vim.keymap.set('n', '<CR>', api.node.open.edit, opts('Open'))
--     vim.keymap.set('n', 'o', api.node.open.edit, opts('Open'))
--     vim.keymap.set('n', 'h', api.node.navigate.parent_close, opts('Close Parent'))
--     vim.keymap.set('n', 'v', api.node.open.vertical, opts('Open in Vertical Split'))
--     vim.keymap.set('n', '<C-t>', api.tree.change_root_to_parent, opts('Up'))
--     vim.keymap.set('n', '?', api.tree.toggle_help, opts('Help'))
-- end
--
-- require("nvim-tree").setup({
--     update_focused_file = {
--         enable = true,
--         update_cwd = true,
--     },
--     renderer = {
--         root_folder_modifier = ":t",
--         -- These icons are visible when you install web-devicons
--         icons = {
--             glyphs = {
--                 default = "",
--                 symlink = "",
--                 folder = {
--                     arrow_open = "",
--                     arrow_closed = "",
--                     default = "",
--                     open = "",
--                     empty = "",
--                     empty_open = "",
--                     symlink = "",
--                     symlink_open = "",
--                 },
--                 git = {
--                     unstaged = "",
--                     staged = "S",
--                     unmerged = "",
--                     renamed = "➜",
--                     untracked = "U",
--                     deleted = "",
--                     ignored = "◌",
--                 },
--             },
--         },
--     },
--     diagnostics = {
--         enable = true,
--         show_on_dirs = true,
--         icons = {
--             hint = "",
--             info = "",
--             warning = "",
--             error = "",
--         },
--     },
--     view = {
--         width = 30,
--         side = "left",
--         relativenumber = true,
--     },
--     on_attach = my_on_attach, -- Custom keybindings
-- })
